name: Deploy to Server

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    types:
      - closed
  workflow_dispatch:

jobs:
  deploy:
    runs-on: github-runner-b2_micro
    if: github.event.pull_request.merged == true || github.event_name != 'pull_request'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/your_app_name:latest

      - name: Deploy to server
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_LOGIN: ${{ secrets.SERVER_LOGIN }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          scp -i private_key.pem -r . $SERVER_LOGIN@$SERVER_IP:/path/to/your/app/directory
          ssh -i private_key.pem $SERVER_LOGIN@$SERVER_IP "cd /path/to/your/app/directory && python your_app.py"
          rm -f private_key.pem
